name: Collect USA Product Trends

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run collector
        run: npm run collect
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add products/hot_all.json
          git commit -m "Auto-update US product trends" || echo "No changes"
          git push
