name: Keyword Tracker (Google Trends)

on:
  schedule:
    - cron: '0 */3 * * *'   # every 3 hours
  workflow_dispatch:        # allow manual run (trial)

permissions:
  contents: read
  pages: write

jobs:
  run-keyword-tracker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scrapers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js  (use 20 for compatibility)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run keyword tracker
        run: node keyword_tracker.js

      - name: Show output summary
        run: ls -lah out || true

      - name: Publish results to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
