name: keyword-tracker

on:
  push:
    paths:
      - 'scrapers/**'
      - 'package.json'
      - '.github/workflows/keyword-tracker.yml'
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run keyword tracker
        run: npm start

      - name: List output file (debug)
        run: |
          echo "Output dir contents:"
          ls -la scrapers/out/keywords || true
          if [ -f scrapers/out/keywords/keyword_hot.json ]; then
            echo "File exists: scrapers/out/keywords/keyword_hot.json"
            wc -c scrapers/out/keywords/keyword_hot.json || true
          fi
