name: Run Market Watcher Scraper

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:        # allows manual run from Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: npm run scrape

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add products/hot_all.json keywords/keyword_hot.json
          git commit -m "Auto-update scraped data [skip ci]" || echo "No changes to commit"
          git push origin main
