name: Scrape Market Data (Every 6 Hours)

on:
  schedule:
    - cron: "0 */6 * * *"   # runs at 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:         # allow manual runs from Actions tab

permissions:
  contents: write            # required to push changes

concurrency:
  group: scrape-market-data
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: npm run scrape

      - name: Commit and push results (if any)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add products/ keywords/
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "Auto-update scraped data ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
          git push origin main
