name: Shopify Scrape & Commit

on:
  schedule:
    - cron: '0 */1 * * *'   # runs every hour (adjust as needed)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scrapers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean npm cache (runner)
        run: |
          npm cache clean --force || true

      - name: Install dependencies (force fresh fetch)
        run: |
          # remove any leftover state that could cause integrity issues
          rm -rf node_modules package-lock.json || true
          # force a fresh fetch; prefer-online avoids using stale local cache,
          # --force helps in systems where tarball checksums are problematic.
          npm install --legacy-peer-deps --no-audit --prefer-online --force --registry=https://registry.npmjs.org/

      - name: Show node & npm and installed deps
        run: |
          node -v
          npm -v
          npm ls --depth=0 || true

      - name: Run scraper pipeline (always runs shopify.js)
        run: |
          set -e
          node shopify.js
          node diff_shopify_snapshots.js || true
          node build_hot_all.js || true
          node keyword_tracker.js || true

      - name: List outputs
        run: |
          echo "Contents of out directory:"
          ls -lah out || true
          echo "Products (out/products):"
          ls -lah out/products || true
          echo "Keywords (out/keywords):"
          ls -lah out/keywords || true

      - name: Commit generated files to repo
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A scrapers/out/products || true
          git add -A scrapers/out/keywords || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update scraper output [ci skip]"
            git push
          else
            echo "No changes to commit."
          fi
