name: Verify Secrets

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print whether secrets are present (safe)
        env:
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${SERP_API_KEY:-}" ]; then echo "❌ SERP_API_KEY missing"; exit 1; fi
          if [ -z "${NEWS_API_KEY:-}" ]; then echo "❌ NEWS_API_KEY missing"; exit 1; fi
          echo "✅ SERP_API_KEY present, length: ${#SERP_API_KEY}"
          echo "✅ NEWS_API_KEY present, length: ${#NEWS_API_KEY}"
